version: '3.7'


services:
  frontend:
    image: serjke88/time-app-frontent-dev
    restart: always
    ports:
      - '3000:3000'
  api:
    image: serjke88/time-app-api-dev
    restart: always
    depends_on:
      - mysql
    ports:
      - '5555:5000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: 'password'
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - my_sql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'


volumes:
  my_sql_data_pub: